### ISSUE TITLE
ie11 error (blank screen)

### ISSUE THREAD

**Issue by mtx62** [valterlorran/vuejs-localization#4]
Greetings,
When I'm using this library I can't get any view at ie11 (blank screen) so hopefully if you can solve this problem quick because this a good library.

Best regards
Abdulaziz Noor

**Comment by kirschkern** [comment]
The reason is, that the library uses ES2015 method notations but doesn't add the relevant dependencies. 

You may directly change the source at the following places:

```
Object.defineProperty(Vue.prototype, '$lang', {
    get () { return this.$root._lang }
});
```

and

```
Vue.mixin({
    beforeCreate () {
        Vue.util.defineReactive(this, '_lang',  new Lang({lang:default_lang}));
    }
});
```
Change `get ()` to `get: function()` and change `beforeCreate ()` to `beforeCreate: function ()`.
The source can be found at: node_modules\vuejs-localization\index.js

I hope to see this fixed in the next update.

**Comment by mtx62** [comment]
Thank you and I will try your solution
