### ISSUE TITLE
Error during build production

### ISSUE THREAD

**Issue by jztan** [valterlorran/vuejs-localization#8]
Got following error during execute "npm run build",

> ERROR in static/js/vendor.7991829f1d3ff15d7f74.js from UglifyJs
> Unexpected token: punc (() [./~/vuejs-localization/index.js:67,0][static/js/vendor.7991829f1d3ff15d7f74.js:17802,6]

Any ideas how to address this?

**Comment by azizsafudin** [comment]
@jztan hey I had the same problem. Apparently uglifyjs is not able to understand ES6. This shouldn't be a problem since the latest commit was to remove ES6 syntax, but apparently the latest npm version is not this latest [commit](https://github.com/valterlorran/vuejs-localization/commit/bdb61fb3846e427e17821bfc51143f67dda7c870). 

Solutions:
You can either change your uglifyjs dependency to the #harmony fork, but this is more troublesome. [StackOverflow 1](https://stackoverflow.com/questions/42375468/uglify-syntaxerror-unexpected-token-punc)
[StackOverflow 2](https://stackoverflow.com/questions/43162237/syntaxerror-unexpected-token-punc)

Best solution that worked for me is to set the dependency in package.json directly to the github's latest commit.   
`"vuejs-localization": "git://github.com/valterlorran/vuejs-localization.git#bdb61fb3846e427e17821bfc51143f67dda7c870"`
But this isn't a long term solution, hopefully the npm package will be updated soon.

You can fix this issue and issue #6 by updating the npm package. @valterlorran

**Comment by jztan** [comment]
@xmodulus thanks for your reply.
Actually i managed to address this issue by including it into my webpack configuration,

   module: {
     rules: [
       {
         test: /\.vue$/,
         loader: 'vue-loader',
         options: vueLoaderConfig
       },
       {
         test: /\.js$/,
         loader: 'babel-loader',
         include: [resolve('src'), resolve('test')**, resolve('node_modules/vuejs-localization')**]
       },
